"use client";

import { useState } from 'react';
import { Search, Sparkles, BarChart2, PieChart, AlertCircle, FileText, Download, FileQuestion } from 'lucide-react';

export default function AIReportingDashboard() {
  const [query, setQuery] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [resultType, setResultType] = useState<'empty' | 'overdue_jobs' | 'revenue_by_team' | 'unpaid_invoices' | 'missing_documents'>('empty');

  const handleSearch = (e: React.FormEvent) => {
    e.preventDefault();
    if (!query.trim()) return;

    setIsSearching(true);
    setResultType('empty');

    setTimeout(() => {
      const q = query.toLowerCase();
      if (q.includes('overdue') && (q.includes('job') || q.includes('project'))) {
        setResultType('overdue_jobs');
      } else if (q.includes('revenue') || q.includes('team') || q.includes('clocked')) {
        setResultType('revenue_by_team');
      } else if (q.includes('unpaid') || q.includes('invoice') || q.includes('billing')) {
        setResultType('unpaid_invoices');
      } else if (q.includes('missing') || q.includes('document')) {
        setResultType('missing_documents');
      } else {
        // Default fallback to show *something* impressive
        setResultType('revenue_by_team');
      }
      setIsSearching(false);
    }, 1200);
  };

  const setSampleQuery = (text: string) => {
    setQuery(text);
    // Auto submit isn't implemented here just setting text
  };

  return (
    <div className="p-6 max-w-6xl mx-auto min-h-[80vh] flex flex-col">
      <div className="text-center mb-8">
        <h1 className="text-3xl font-bold flex items-center justify-center gap-2 mb-2">
          <Sparkles className="text-purple-500" />
          AI Data Assistant
        </h1>
        <p className="text-gray-500">Ask any question about your firm's data in plain English.</p>
      </div>

      {/* Query Bar */}
      <div className="bg-white p-2 rounded-2xl shadow-lg border flex items-center mb-8 max-w-3xl mx-auto w-full">
        <div className="pl-4 text-gray-400"><Search size={24} /></div>
        <form onSubmit={handleSearch} className="flex-1 px-4">
          <input 
            type="text" 
            className="w-full py-4 bg-transparent outline-none text-lg text-gray-800"
            placeholder="e.g. Show me all overdue jobs by team member..."
            value={query} onChange={e => setQuery(e.target.value)}
          />
        </form>
        <button 
          onClick={handleSearch} 
          disabled={isSearching}
          className="bg-purple-600 hover:bg-purple-700 text-white font-medium px-6 py-3 rounded-xl transition shadow-md"
        >
          {isSearching ? <span className="animate-pulse">Thinking...</span> : 'Analyze'}
        </button>
      </div>

      {/* Sample Queries (Empty State) */}
      {resultType === 'empty' && !isSearching && (
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-4xl mx-auto mt-8">
            <div onClick={() => setSampleQuery("Show me all overdue jobs")} className="bg-white p-4 rounded-xl border border-gray-100 hover:border-purple-300 hover:shadow-md cursor-pointer transition flex items-center gap-3">
               <div className="bg-red-50 text-red-600 p-2 rounded-lg"><AlertCircle size={20} /></div>
               <span className="text-gray-700 font-medium">"Show me all overdue jobs"</span>
            </div>
            <div onClick={() => setSampleQuery("Revenue generated by team")} className="bg-white p-4 rounded-xl border border-gray-100 hover:border-purple-300 hover:shadow-md cursor-pointer transition flex items-center gap-3">
               <div className="bg-green-50 text-green-600 p-2 rounded-lg"><BarChart2 size={20} /></div>
               <span className="text-gray-700 font-medium">"Revenue generated by team"</span>
            </div>
            <div onClick={() => setSampleQuery("List unpaid invoices over $500")} className="bg-white p-4 rounded-xl border border-gray-100 hover:border-purple-300 hover:shadow-md cursor-pointer transition flex items-center gap-3">
               <div className="bg-blue-50 text-blue-600 p-2 rounded-lg"><FileText size={20} /></div>
               <span className="text-gray-700 font-medium">"List unpaid invoices over $500"</span>
            </div>
            <div onClick={() => setSampleQuery("Missing Documents Report")} className="bg-white p-4 rounded-xl border border-gray-100 hover:border-purple-300 hover:shadow-md cursor-pointer transition flex items-center gap-3">
               <div className="bg-orange-50 text-orange-600 p-2 rounded-lg"><FileQuestion size={20} /></div>
               <span className="text-gray-700 font-medium">"Missing Documents Report"</span>
            </div>
        </div>
      )}

      {/* Results Area */}
      {resultType !== 'empty' && !isSearching && (
        <div className="flex-1 bg-white rounded-2xl shadow-sm border p-8 animate-in slide-in-from-bottom-4">
          
          {/* Overdue Jobs Result */}
          {resultType === 'overdue_jobs' && (
             <div>
                <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                  <PieChart className="text-purple-600"/> 
                  Overdue Jobs Distribution
                </h3>
                <div className="grid grid-cols-2 gap-8">
                   <div className="space-y-4">
                      {[{ label: 'Frank Wilson', val: 3, pct: 60, col: 'bg-red-500' },
                        { label: 'Sarah Connor', val: 1, pct: 20, col: 'bg-orange-400' },
                        { label: 'Luca Pacioli', val: 1, pct: 20, col: 'bg-yellow-400' }].map(t => (
                         <div key={t.label}>
                            <div className="flex justify-between text-sm mb-1">
                               <span className="font-medium text-gray-700">{t.label}</span>
                               <span className="text-gray-500">{t.val} Jobs</span>
                            </div>
                            <div className="w-full bg-gray-100 rounded-full h-3">
                               <div className={`h-3 rounded-full ${t.col}`} style={{ width: `${t.pct}%` }}></div>
                            </div>
                         </div>
                      ))}
                   </div>
                   <div className="bg-gray-50 p-6 rounded-xl border flex flex-col items-center justify-center text-center">
                     <span className="text-red-600 bg-red-100 font-bold p-3 rounded-full mb-3"><AlertCircle size={32}/></span>
                     <p className="text-4xl font-extrabold text-gray-800">5</p>
                     <p className="text-gray-500">Total Overdue Jobs Today</p>
                   </div>
                </div>
             </div>
          )}

          {/* Revenue Result */}
          {resultType === 'revenue_by_team' && (
             <div>
                <h3 className="text-xl font-bold mb-6 flex items-center gap-2">
                  <BarChart2 className="text-purple-600"/> 
                  Billed Revenue Attribution
                </h3>
                <div className="flex bg-gray-50 p-6 rounded-xl border h-64 gap-4 items-end justify-around p-8">
                  {/* Mock Vertical Bar Chart */}
                  {[{ label: 'Frank W.', val: 45000, h: '70%'}, { label: 'Sarah C.', val: 52000, h: '85%'}, { label: 'Luca P.', val: 28000, h: '45%'}].map(b => (
                    <div key={b.label} className="flex flex-col items-center gap-2 w-full">
                       <span className="text-sm font-bold text-gray-600">${(b.val / 1000).toFixed(0)}k</span>
                       <div className="w-full max-w-16 bg-purple-500 rounded-t-md hover:bg-purple-400 transition" style={{ height: b.h }}></div>
                       <span className="text-xs font-medium text-gray-500">{b.label}</span>
                    </div>
                  ))}
                </div>
             </div>
          )}

          {/* Missing Documents Result */}
          {resultType === 'missing_documents' && (
             <div>
                <div className="flex items-center justify-between mb-6">
                  <h3 className="text-xl font-bold flex items-center gap-2">
                    <FileQuestion className="text-purple-600"/> 
                    Missing Documents & Client Checklists
                  </h3>
                  <button onClick={() => alert('Downloading CSV Report...')} className="bg-purple-50 text-purple-700 hover:bg-purple-100 border border-purple-200 px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2 transition">
                    <Download size={16}/> Export CSV
                  </button>
                </div>
                <div className="bg-orange-50/50 rounded-xl border p-4 mb-6">
                   <p className="text-sm text-gray-700 flex items-center gap-2"><Sparkles size={16} className="text-orange-500" /> These 3 active engagements currently have outstanding documents or unfilled organizer items.</p>
                </div>
                <table className="w-full text-left text-sm">
                  <thead className="bg-gray-50 border-y">
                    <tr><th className="p-3">Client</th><th className="p-3">Project Type</th><th className="p-3">Compliance Blockers</th><th className="p-3 text-right">Days Waiting</th></tr>
                  </thead>
                  <tbody className="divide-y text-gray-700">
                    <tr>
                      <td className="p-3 font-medium">Stark Industries</td>
                      <td className="p-3">Corporate Tax Return (T2)</td>
                      <td className="p-3">
                        <span className="text-red-700 bg-red-50 border border-red-100 px-2 py-1 rounded text-xs font-semibold">Missing Articles of Incorporation</span>
                      </td>
                      <td className="p-3 text-right"><span className="font-bold text-gray-900">14 Days</span></td>
                    </tr>
                    <tr>
                      <td className="p-3 font-medium">Wayne Enterprises</td>
                      <td className="p-3">Annual Bookkeeping</td>
                      <td className="p-3">
                        <span className="text-orange-700 bg-orange-50 border border-orange-100 px-2 py-1 rounded text-xs font-semibold">Missing Bank Statements (Q4)</span>
                      </td>
                      <td className="p-3 text-right"><span className="font-bold text-gray-900">8 Days</span></td>
                    </tr>
                    <tr>
                      <td className="p-3 font-medium">Jane Doe</td>
                      <td className="p-3">Personal Tax (T1)</td>
                      <td className="p-3">
                        <span className="text-blue-700 bg-blue-50 border border-blue-100 px-2 py-1 rounded text-xs font-semibold">T4 Slips Outstanding</span>
                      </td>
                      <td className="p-3 text-right"><span className="font-bold text-gray-900">2 Days</span></td>
                    </tr>
                  </tbody>
                </table>
             </div>
          )}

        </div>
      )}
    </div>
  );
}
